# This is a basic workflow to help you get started with Actions

name: Contribution Charts

# Controls when the workflow will run
on:
 schedule:
     - cron: "0 0 * * *"
 workflow_dispatch: 
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
     # this will generate the contribution graph into an 'images' folder
    - uses: JBraunsmaJr/contributiongraph@v1
      with:
         token: ${{ secrets.METRICS_TOKEN }}
         viewby: day
         farback: 31
    
    # simply update anything within the images folder that got updated...
    - uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: Updating Contribution Graph
        file_pattern: images/*
